#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "opensearch"
name = "OpenSearch"
description.en = "Open source distributed and RESTful search engine"
description.fr = "Moteur de recherche RESTful et open-source"

version = "2.9.0~ynh4"

maintainers = ["fflorent"]

[upstream]
license = "Apache-2.0"
website = "https://opensearch.org"
demo = "https://playground.opensearch.org/app/home"
admindoc = "https://opensearch.org/docs/latest/"
code = "https://github.com/opensearch-project/OpenSearch"
cpe = "cpe:2.3:a:amazon:opensearch"

[integration]
yunohost = ">= 11.2.20"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "300M"
ram.build = "600M"
ram.runtime = "600M"

[install]

[resources]
    [resources.sources.main]
    amd64.url = "https://artifacts.opensearch.org/releases/bundle/opensearch/2.9.0/opensearch-2.9.0-linux-x64.tar.gz"
    amd64.sha256 = "03d623c2d99a7100c2f0faddc8ffda8ba27eae8aa63ff6f3f7dad2337be8b68c"
    arm64.url = "https://artifacts.opensearch.org/releases/bundle/opensearch/2.9.0/opensearch-2.9.0-linux-arm64.tar.gz"
    arm64.sha256 = "ba6045e58d433f64f09d92565e308553647bfd3f1193346a1716f7f66e4aad5a"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    main.default = 9200
