#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================



source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup --src_path="$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup --src_path="$data_dir" --is_big

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup --src_path="/etc/logrotate.d/$app"

if [ "${container:-}" != "lxc" ]; then # lxc doesn't allow sysctl to play with kernel options.
    ynh_backup --src_path="/etc/sysctl.d/90-max_map_count-opensearch.conf"
fi

ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
