#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DEFAULT VALUES FOR CONFIGURATION
#=================================================

ynh_app_setting_set --key="xms" --value="256m"

ynh_app_setting_set --key="xmx" --value="1g"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD CONFIGURATIONS
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="opensearch.yml" --destination="$install_dir/config/opensearch.yml"
ynh_config_add --template="jvm.options" --destination="$install_dir/config/jvm.options.d/yunohost.options"

#=================================================
# INCREASE MAX_MAP_COUNT
#=================================================
ynh_script_progression "Increasing maximum map count (sysctl)..."

if [ "${container:-}" != "lxc" ]; then # lxc doesn't allow sysctl to play with kernel options.
    # Increase the maximum number of files inotify can monitor.
    ynh_config_add --template="90-max_map_count-opensearch.conf" --destination="/etc/sysctl.d/90-max_map_count-$app.conf"

    # Then, reload the kernel configuration.
    sysctl -p /etc/sysctl.d/90-max_map_count-opensearch.conf
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Distributed and RESTful search engine" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
