#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

if [ -e "/etc/sysctl.d/90-max_map_count-opensearch.conf" ]; then
    ynh_secure_remove --file="/etc/sysctl.d/90-max_map_count-opensearch.conf"
    # Reload the kernel configuration.
    if ! [ "${container:-}" = "lxc" ]; then # lxc doesn't allow sysctl to play with kernel options.
        sysctl --system
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
