#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

if [ -e "/etc/sysctl.d/90-max_map_count-$app.conf" ]; then
    ynh_safe_rm "/etc/sysctl.d/90-max_map_count-$app.conf"
    # Reload the kernel configuration.
    if ! [ "${container:-}" = "lxc" ]; then # lxc doesn't allow sysctl to play with kernel options.
        sysctl --system
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
