#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

port=$(ynh_app_setting_get --app=$app --key=port)
datadir=$(ynh_app_setting_get --app=$app --key=datadir)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..." --weight=1

# Remove the app directory securely
ynh_secure_remove --file="$final_path"

#=================================================
# REMOVE DATA DIR
#=================================================

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
	ynh_script_progression --message="Removing app data directory..." --weight=1
	ynh_secure_remove --file="$datadir"
fi

#=================================================
# REMOVE PID DIR
#=================================================

ynh_script_progression --message="Removing pid directory..." --weight=1
ynh_secure_remove --file="/run/$app"

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..." --weight=1
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user..." --weight=1

# Delete a system user
ynh_system_user_delete --username=$app

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

if [ -e "/etc/sysctl.d/90-max_map_count-opensearch.conf" ]; then
	ynh_secure_remove --file="/etc/sysctl.d/90-max_map_count-opensearch.conf"
	# Reload the kernel configuration.
	if ! [ "${container:-}" = "lxc" ] # lxc doesn't allow sysctl to play with kernel options.
	then
		sysctl --system
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
